### ISSUE TITLE
Change suggestions in "first steps"

### ISSUE THREAD

**Issue by tramontini** [looqbox/guide#3]
- **Looq Response**
  - This part is ok, but I think that it should be more clearly that this function NEED to be inside the script or it will not work.
  - Maybe it should explain what is `par`? I think that a lot of people really don't know what this is and only put in the scripts because it has to be there.

- **Testing**
  - I think that some users will have problem only with this example. The problem here is that some entities are vector and others are lists (like `$date`), reading this maybe the user pass something like:
  ```
  looq.testQuestion(
    list(
     "$date" = "2018-10-04" 
   )
  )
  ```

  and the right form is:
  ```
  looq.testQuestion(
    list(
     "$date" = list("2018-10-04", "2018-10-04") 
   )
  )
  ```

- I have a feeling that with this example a LOT of developers will create all the script inside the `looq.response` and this should be considered an awful code. Maybe would be great to print the message in other function and show the use of looq.responseFrame..

**Comment by filipefilardi** [comment]
Thanks for the suggestion.

Fixed in [this commit](https://github.com/looqbox/guide/commit/e434a58c34779dadf4b4e07a522c3b5a2de17560)
